
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.rocky.tools.init;

import net.rocky.tools.item.YellowWaterItem;
import net.rocky.tools.item.YellowDiamondSwordItem;
import net.rocky.tools.item.YellowDiamondItem;
import net.rocky.tools.item.YellowDiamondIngotItem;
import net.rocky.tools.item.WaterItem;
import net.rocky.tools.item.VainillaNutellaItem;
import net.rocky.tools.item.ToxicItem;
import net.rocky.tools.item.TotemItem;
import net.rocky.tools.item.SwordsItem;
import net.rocky.tools.item.StrawberryNutellaItem;
import net.rocky.tools.item.StrawberryItem;
import net.rocky.tools.item.StoneItem;
import net.rocky.tools.item.StickItem;
import net.rocky.tools.item.RodajaDePizzaItem;
import net.rocky.tools.item.RedstonenuggetItem;
import net.rocky.tools.item.RedstoneeSwordItem;
import net.rocky.tools.item.RedstoneeShovelItem;
import net.rocky.tools.item.RedstoneePickaxeItem;
import net.rocky.tools.item.RedstoneeHoeItem;
import net.rocky.tools.item.RedstoneeAxeItem;
import net.rocky.tools.item.RedstoneItem;
import net.rocky.tools.item.RedstoneIngotItem;
import net.rocky.tools.item.RedstoneHammerItem;
import net.rocky.tools.item.RedstoneEnchantedAppleItem;
import net.rocky.tools.item.RedstoneAppleItem;
import net.rocky.tools.item.RedWaterItem;
import net.rocky.tools.item.RedTotemItem;
import net.rocky.tools.item.RedSwordItem;
import net.rocky.tools.item.RedShovelItem;
import net.rocky.tools.item.RedReinforcedSwordItem;
import net.rocky.tools.item.RedReinforcedShovelItem;
import net.rocky.tools.item.RedReinforcedPickaxeItem;
import net.rocky.tools.item.RedReinforcedHoeItem;
import net.rocky.tools.item.RedReinforcedAxeItem;
import net.rocky.tools.item.RedPickaxeItem;
import net.rocky.tools.item.RedHoeItem;
import net.rocky.tools.item.RedEmeraldFragmentItem;
import net.rocky.tools.item.RedEmeraldAArmorItem;
import net.rocky.tools.item.RedDiamondSwordItem;
import net.rocky.tools.item.RedDiamondShovelItem;
import net.rocky.tools.item.RedDiamondPickaxeItem;
import net.rocky.tools.item.RedDiamondItem;
import net.rocky.tools.item.RedDiamondIngotItem;
import net.rocky.tools.item.RedDiamondHoeItem;
import net.rocky.tools.item.RedDiamondAxeItem;
import net.rocky.tools.item.RedAxeItem;
import net.rocky.tools.item.RedArmorItem;
import net.rocky.tools.item.RedAppleJuiceVoidItem;
import net.rocky.tools.item.RedAppleJuiceItem;
import net.rocky.tools.item.PurpleWaterItem;
import net.rocky.tools.item.PizzaV2Item;
import net.rocky.tools.item.PizzaItem;
import net.rocky.tools.item.PinkWaterItem;
import net.rocky.tools.item.PetrolleoItem;
import net.rocky.tools.item.PentistItem;
import net.rocky.tools.item.PentistIngotItem;
import net.rocky.tools.item.PALEArmorItem;
import net.rocky.tools.item.OrangeWaterItem;
import net.rocky.tools.item.OptiniumRotItem;
import net.rocky.tools.item.OptiniumPickaxeItem;
import net.rocky.tools.item.OptiniumIngotItem;
import net.rocky.tools.item.OptiniumHammerItem;
import net.rocky.tools.item.OptiniumAxeItem;
import net.rocky.tools.item.OneHundredDollarsItem;
import net.rocky.tools.item.ObsidianSwordItem;
import net.rocky.tools.item.ObsidianShovelItem;
import net.rocky.tools.item.ObsidianPickaxeItem;
import net.rocky.tools.item.ObsidianHoeItem;
import net.rocky.tools.item.ObsidianAxeItem;
import net.rocky.tools.item.ObsidianArmorItem;
import net.rocky.tools.item.NetheriteHammerItem;
import net.rocky.tools.item.MoneyyItem;
import net.rocky.tools.item.MilkItem;
import net.rocky.tools.item.MetalSwordItem;
import net.rocky.tools.item.MetalShovelItem;
import net.rocky.tools.item.MetalPickaxeItem;
import net.rocky.tools.item.MetalItem;
import net.rocky.tools.item.MetalIngotItem;
import net.rocky.tools.item.MetalHoeItem;
import net.rocky.tools.item.MetalAxeItem;
import net.rocky.tools.item.MagnifItem;
import net.rocky.tools.item.MagnifIngotItem;
import net.rocky.tools.item.MagneSwordItem;
import net.rocky.tools.item.MagneShovelItem;
import net.rocky.tools.item.MagnePickaxeItem;
import net.rocky.tools.item.MagneHoeItem;
import net.rocky.tools.item.MagneAxeItem;
import net.rocky.tools.item.MagneArmorItem;
import net.rocky.tools.item.MaceItem;
import net.rocky.tools.item.LightBlueWaterItem;
import net.rocky.tools.item.LapisLazuliHammerItem;
import net.rocky.tools.item.IronHammerItem;
import net.rocky.tools.item.GreenWaterItem;
import net.rocky.tools.item.GreenDiamondSwordItem;
import net.rocky.tools.item.GreenDiamondShovelItem;
import net.rocky.tools.item.GreenDiamondPickaxeItem;
import net.rocky.tools.item.GreenDiamondItem;
import net.rocky.tools.item.GreenDiamondIngotItem;
import net.rocky.tools.item.GreenDiamondHoeItem;
import net.rocky.tools.item.GreenDiamondAxeItem;
import net.rocky.tools.item.GreenAppleJuiceVoidItem;
import net.rocky.tools.item.GreeAppleJuiceItem;
import net.rocky.tools.item.GrapeItem;
import net.rocky.tools.item.GoldPorkchopItem;
import net.rocky.tools.item.GoldPorkchopCookedItem;
import net.rocky.tools.item.GoldMaceItem;
import net.rocky.tools.item.FolliageFragmentItem;
import net.rocky.tools.item.FiveDollarsItem;
import net.rocky.tools.item.FiftyDollarItem;
import net.rocky.tools.item.FantistItem;
import net.rocky.tools.item.EnchantedDiamondAppleItem;
import net.rocky.tools.item.EmeraldaArmorItem;
import net.rocky.tools.item.EmeraldASwordItem;
import net.rocky.tools.item.EmeraldAShovelItem;
import net.rocky.tools.item.EmeraldAPickaxeItem;
import net.rocky.tools.item.EmeraldAHoeItem;
import net.rocky.tools.item.EmeraldAAxeItem;
import net.rocky.tools.item.DirtItem;
import net.rocky.tools.item.DiamondHammerItem;
import net.rocky.tools.item.DiamondHammer3dItem;
import net.rocky.tools.item.DiamondAppleItem;
import net.rocky.tools.item.CursedItem;
import net.rocky.tools.item.CreeperItem;
import net.rocky.tools.item.CortadorItem;
import net.rocky.tools.item.CoppertSwordItem;
import net.rocky.tools.item.CoppertShovelItem;
import net.rocky.tools.item.CoppertPickaxeItem;
import net.rocky.tools.item.CoppertHoeItem;
import net.rocky.tools.item.CoppertAxeItem;
import net.rocky.tools.item.CoppernuggetItem;
import net.rocky.tools.item.CopperItem;
import net.rocky.tools.item.ColsitemItem;
import net.rocky.tools.item.ColosalItem;
import net.rocky.tools.item.ChocolateNutellaItem;
import net.rocky.tools.item.CherrySwordItem;
import net.rocky.tools.item.CherryShovelItem;
import net.rocky.tools.item.CherryPickaxeItem;
import net.rocky.tools.item.CherryHoeItem;
import net.rocky.tools.item.CherryAxeItem;
import net.rocky.tools.item.CherryArmorItem;
import net.rocky.tools.item.CandybastonItem;
import net.rocky.tools.item.BrownWaterItem;
import net.rocky.tools.item.BottleItem;
import net.rocky.tools.item.Blue_RubyIngotItem;
import net.rocky.tools.item.BlueWaterItem;
import net.rocky.tools.item.BlueRubySwordItem;
import net.rocky.tools.item.BlueRubyShovelItem;
import net.rocky.tools.item.BlueRubyPickaxeItem;
import net.rocky.tools.item.BlueRubyHoeItem;
import net.rocky.tools.item.BlueRubyAxeItem;
import net.rocky.tools.item.BlueRubyArmorItem;
import net.rocky.tools.item.BlueDiamondTotemItem;
import net.rocky.tools.item.BlueBrickArmorItem;
import net.rocky.tools.item.BlackTotemItem;
import net.rocky.tools.item.BernyDimencionItem;
import net.rocky.tools.item.BedrockArmorItem;
import net.rocky.tools.item.BananaItem;
import net.rocky.tools.item.AxoltlItem;
import net.rocky.tools.item.ArcoirisWaterItem;
import net.rocky.tools.item.AquaWaterItem;
import net.rocky.tools.item.AquaSwordItem;
import net.rocky.tools.item.AquaShovelItem;
import net.rocky.tools.item.AquaPickaxeItem;
import net.rocky.tools.item.AquaHoeItem;
import net.rocky.tools.item.AquaDarkSwordItem;
import net.rocky.tools.item.AquaDarkShovelItem;
import net.rocky.tools.item.AquaDarkPickaxeItem;
import net.rocky.tools.item.AquaDarkHoeItem;
import net.rocky.tools.item.AquaDarkAxeItem;
import net.rocky.tools.item.AquaDarkArmorItem;
import net.rocky.tools.item.AquaAxeItem;
import net.rocky.tools.item.AquaArmorItem;
import net.rocky.tools.item.AmethystSwordItem;
import net.rocky.tools.item.AmethystShovelItem;
import net.rocky.tools.item.AmethystPickaxeItem;
import net.rocky.tools.item.AmethystHoeItem;
import net.rocky.tools.item.AmethystAxeItem;
import net.rocky.tools.item.AmethystArmorItem;
import net.rocky.tools.item.AirItem;
import net.rocky.tools.TheToolsAndOtherMod;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.SpawnEggItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;

import java.util.function.Function;

public class TheToolsAndOtherModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(TheToolsAndOtherMod.MODID);
	public static final DeferredItem<Item> AMETHYST_ARMOR_HELMET = register("amethyst_armor_helmet", AmethystArmorItem.Helmet::new);
	public static final DeferredItem<Item> AMETHYST_ARMOR_CHESTPLATE = register("amethyst_armor_chestplate", AmethystArmorItem.Chestplate::new);
	public static final DeferredItem<Item> AMETHYST_ARMOR_LEGGINGS = register("amethyst_armor_leggings", AmethystArmorItem.Leggings::new);
	public static final DeferredItem<Item> AMETHYST_ARMOR_BOOTS = register("amethyst_armor_boots", AmethystArmorItem.Boots::new);
	public static final DeferredItem<Item> AMETHYST_PICKAXE = register("amethyst_pickaxe", AmethystPickaxeItem::new);
	public static final DeferredItem<Item> AMETHYST_AXE = register("amethyst_axe", AmethystAxeItem::new);
	public static final DeferredItem<Item> AMETHYST_SWORD = register("amethyst_sword", AmethystSwordItem::new);
	public static final DeferredItem<Item> AMETHYST_SHOVEL = register("amethyst_shovel", AmethystShovelItem::new);
	public static final DeferredItem<Item> AMETHYST_HOE = register("amethyst_hoe", AmethystHoeItem::new);
	public static final DeferredItem<Item> CHERRY_ARMOR_HELMET = register("cherry_armor_helmet", CherryArmorItem.Helmet::new);
	public static final DeferredItem<Item> CHERRY_ARMOR_CHESTPLATE = register("cherry_armor_chestplate", CherryArmorItem.Chestplate::new);
	public static final DeferredItem<Item> CHERRY_ARMOR_LEGGINGS = register("cherry_armor_leggings", CherryArmorItem.Leggings::new);
	public static final DeferredItem<Item> CHERRY_ARMOR_BOOTS = register("cherry_armor_boots", CherryArmorItem.Boots::new);
	public static final DeferredItem<Item> CHERRY_PICKAXE = register("cherry_pickaxe", CherryPickaxeItem::new);
	public static final DeferredItem<Item> CHERRY_AXE = register("cherry_axe", CherryAxeItem::new);
	public static final DeferredItem<Item> CHERRY_SWORD = register("cherry_sword", CherrySwordItem::new);
	public static final DeferredItem<Item> CHERRY_SHOVEL = register("cherry_shovel", CherryShovelItem::new);
	public static final DeferredItem<Item> CHERRY_HOE = register("cherry_hoe", CherryHoeItem::new);
	public static final DeferredItem<Item> BLUE_RUBY_INGOT = register("blue_ruby_ingot", Blue_RubyIngotItem::new);
	public static final DeferredItem<Item> BLUE_RUBY_BLOCK = block(TheToolsAndOtherModBlocks.BLUE_RUBY_BLOCK);
	public static final DeferredItem<Item> BLUERUBYORE = block(TheToolsAndOtherModBlocks.BLUERUBYORE);
	public static final DeferredItem<Item> BLUE_RUBY_PICKAXE = register("blue_ruby_pickaxe", BlueRubyPickaxeItem::new);
	public static final DeferredItem<Item> BLUE_RUBY_AXE = register("blue_ruby_axe", BlueRubyAxeItem::new);
	public static final DeferredItem<Item> BLUE_RUBY_SWORD = register("blue_ruby_sword", BlueRubySwordItem::new);
	public static final DeferredItem<Item> BLUE_RUBY_SHOVEL = register("blue_ruby_shovel", BlueRubyShovelItem::new);
	public static final DeferredItem<Item> BLUE_RUBY_HOE = register("blue_ruby_hoe", BlueRubyHoeItem::new);
	public static final DeferredItem<Item> BLUE_RUBY_ARMOR_HELMET = register("blue_ruby_armor_helmet", BlueRubyArmorItem.Helmet::new);
	public static final DeferredItem<Item> BLUE_RUBY_ARMOR_CHESTPLATE = register("blue_ruby_armor_chestplate", BlueRubyArmorItem.Chestplate::new);
	public static final DeferredItem<Item> BLUE_RUBY_ARMOR_LEGGINGS = register("blue_ruby_armor_leggings", BlueRubyArmorItem.Leggings::new);
	public static final DeferredItem<Item> BLUE_RUBY_ARMOR_BOOTS = register("blue_ruby_armor_boots", BlueRubyArmorItem.Boots::new);
	public static final DeferredItem<Item> REDSTONE_HELMET = register("redstone_helmet", RedstoneItem.Helmet::new);
	public static final DeferredItem<Item> REDSTONE_CHESTPLATE = register("redstone_chestplate", RedstoneItem.Chestplate::new);
	public static final DeferredItem<Item> REDSTONE_LEGGINGS = register("redstone_leggings", RedstoneItem.Leggings::new);
	public static final DeferredItem<Item> REDSTONE_BOOTS = register("redstone_boots", RedstoneItem.Boots::new);
	public static final DeferredItem<Item> REDSTONE_INGOT = register("redstone_ingot", RedstoneIngotItem::new);
	public static final DeferredItem<Item> REDSTONENUGGET = register("redstonenugget", RedstonenuggetItem::new);
	public static final DeferredItem<Item> REDSTONEE_PICKAXE = register("redstonee_pickaxe", RedstoneePickaxeItem::new);
	public static final DeferredItem<Item> REDSTONEE_AXE = register("redstonee_axe", RedstoneeAxeItem::new);
	public static final DeferredItem<Item> REDSTONEE_SWORD = register("redstonee_sword", RedstoneeSwordItem::new);
	public static final DeferredItem<Item> REDSTONEE_SHOVEL = register("redstonee_shovel", RedstoneeShovelItem::new);
	public static final DeferredItem<Item> REDSTONEE_HOE = register("redstonee_hoe", RedstoneeHoeItem::new);
	public static final DeferredItem<Item> GREEN_WATER_BUCKET = register("green_water_bucket", GreenWaterItem::new);
	public static final DeferredItem<Item> RED_WATER_BUCKET = register("red_water_bucket", RedWaterItem::new);
	public static final DeferredItem<Item> COPPER_HELMET = register("copper_helmet", CopperItem.Helmet::new);
	public static final DeferredItem<Item> COPPER_CHESTPLATE = register("copper_chestplate", CopperItem.Chestplate::new);
	public static final DeferredItem<Item> COPPER_LEGGINGS = register("copper_leggings", CopperItem.Leggings::new);
	public static final DeferredItem<Item> COPPER_BOOTS = register("copper_boots", CopperItem.Boots::new);
	public static final DeferredItem<Item> COPPERT_PICKAXE = register("coppert_pickaxe", CoppertPickaxeItem::new);
	public static final DeferredItem<Item> COPPERT_AXE = register("coppert_axe", CoppertAxeItem::new);
	public static final DeferredItem<Item> COPPERT_SWORD = register("coppert_sword", CoppertSwordItem::new);
	public static final DeferredItem<Item> COPPERT_SHOVEL = register("coppert_shovel", CoppertShovelItem::new);
	public static final DeferredItem<Item> COPPERT_HOE = register("coppert_hoe", CoppertHoeItem::new);
	public static final DeferredItem<Item> COPPERNUGGET = register("coppernugget", CoppernuggetItem::new);
	public static final DeferredItem<Item> RED_REINFORCED_BRICKS = block(TheToolsAndOtherModBlocks.RED_REINFORCED_BRICKS);
	public static final DeferredItem<Item> BERNY_WOOD = block(TheToolsAndOtherModBlocks.BERNY_WOOD);
	public static final DeferredItem<Item> BERNY_LOG = block(TheToolsAndOtherModBlocks.BERNY_LOG);
	public static final DeferredItem<Item> BERNY_PLANKS = block(TheToolsAndOtherModBlocks.BERNY_PLANKS);
	public static final DeferredItem<Item> BERNY_LEAVES = block(TheToolsAndOtherModBlocks.BERNY_LEAVES);
	public static final DeferredItem<Item> BERNY_STAIRS = block(TheToolsAndOtherModBlocks.BERNY_STAIRS);
	public static final DeferredItem<Item> BERNY_SLAB = block(TheToolsAndOtherModBlocks.BERNY_SLAB);
	public static final DeferredItem<Item> BERNY_FENCE = block(TheToolsAndOtherModBlocks.BERNY_FENCE);
	public static final DeferredItem<Item> BERNY_FENCE_GATE = block(TheToolsAndOtherModBlocks.BERNY_FENCE_GATE);
	public static final DeferredItem<Item> BERNY_PRESSURE_PLATE = block(TheToolsAndOtherModBlocks.BERNY_PRESSURE_PLATE);
	public static final DeferredItem<Item> BERNY_BUTTON = block(TheToolsAndOtherModBlocks.BERNY_BUTTON);
	public static final DeferredItem<Item> MAGNIFICTECIOSS = block(TheToolsAndOtherModBlocks.MAGNIFICTECIOSS);
	public static final DeferredItem<Item> MAGNIFICTECIOSS_REINFORCED = block(TheToolsAndOtherModBlocks.MAGNIFICTECIOSS_REINFORCED);
	public static final DeferredItem<Item> BANANA = register("banana", BananaItem::new);
	public static final DeferredItem<Item> BANANA_FRUIT = block(TheToolsAndOtherModBlocks.BANANA_FRUIT);
	public static final DeferredItem<Item> BERNY_DIMENCION = register("berny_dimencion", BernyDimencionItem::new);
	public static final DeferredItem<Item> DIAMOND_HAMMER = register("diamond_hammer", DiamondHammerItem::new);
	public static final DeferredItem<Item> LAPIS_LAZULI_HAMMER = register("lapis_lazuli_hammer", LapisLazuliHammerItem::new);
	public static final DeferredItem<Item> REDSTONE_HAMMER = register("redstone_hammer", RedstoneHammerItem::new);
	public static final DeferredItem<Item> IRON_HAMMER = register("iron_hammer", IronHammerItem::new);
	public static final DeferredItem<Item> NETHERITE_HAMMER = register("netherite_hammer", NetheriteHammerItem::new);
	public static final DeferredItem<Item> STICK = register("stick", StickItem::new);
	public static final DeferredItem<Item> OBSIDIAN_ARMOR_HELMET = register("obsidian_armor_helmet", ObsidianArmorItem.Helmet::new);
	public static final DeferredItem<Item> OBSIDIAN_ARMOR_CHESTPLATE = register("obsidian_armor_chestplate", ObsidianArmorItem.Chestplate::new);
	public static final DeferredItem<Item> OBSIDIAN_ARMOR_LEGGINGS = register("obsidian_armor_leggings", ObsidianArmorItem.Leggings::new);
	public static final DeferredItem<Item> OBSIDIAN_ARMOR_BOOTS = register("obsidian_armor_boots", ObsidianArmorItem.Boots::new);
	public static final DeferredItem<Item> OBSIDIAN_PICKAXE = register("obsidian_pickaxe", ObsidianPickaxeItem::new);
	public static final DeferredItem<Item> OBSIDIAN_AXE = register("obsidian_axe", ObsidianAxeItem::new);
	public static final DeferredItem<Item> OBSIDIAN_SWORD = register("obsidian_sword", ObsidianSwordItem::new);
	public static final DeferredItem<Item> OBSIDIAN_SHOVEL = register("obsidian_shovel", ObsidianShovelItem::new);
	public static final DeferredItem<Item> OBSIDIAN_HOE = register("obsidian_hoe", ObsidianHoeItem::new);
	public static final DeferredItem<Item> MAGNE_LOG = block(TheToolsAndOtherModBlocks.MAGNE_LOG);
	public static final DeferredItem<Item> MAGNE_PLANKS = block(TheToolsAndOtherModBlocks.MAGNE_PLANKS);
	public static final DeferredItem<Item> MAGNE_WOOD = block(TheToolsAndOtherModBlocks.MAGNE_WOOD);
	public static final DeferredItem<Item> MAGNE_DOOR = doubleBlock(TheToolsAndOtherModBlocks.MAGNE_DOOR);
	public static final DeferredItem<Item> MAGNE_TRAPDOOR = block(TheToolsAndOtherModBlocks.MAGNE_TRAPDOOR);
	public static final DeferredItem<Item> MAGNE_FENCE = block(TheToolsAndOtherModBlocks.MAGNE_FENCE);
	public static final DeferredItem<Item> MAGNE_FENCE_GATE = block(TheToolsAndOtherModBlocks.MAGNE_FENCE_GATE);
	public static final DeferredItem<Item> MAGNE_PRESSURE_PLATE = block(TheToolsAndOtherModBlocks.MAGNE_PRESSURE_PLATE);
	public static final DeferredItem<Item> MAGNE_BUTTOM = block(TheToolsAndOtherModBlocks.MAGNE_BUTTOM);
	public static final DeferredItem<Item> AQUA_LOG = block(TheToolsAndOtherModBlocks.AQUA_LOG);
	public static final DeferredItem<Item> AQUA_PLANKS = block(TheToolsAndOtherModBlocks.AQUA_PLANKS);
	public static final DeferredItem<Item> AQUA_WOOD = block(TheToolsAndOtherModBlocks.AQUA_WOOD);
	public static final DeferredItem<Item> AQUA_DOOR = doubleBlock(TheToolsAndOtherModBlocks.AQUA_DOOR);
	public static final DeferredItem<Item> AQUA_TRAPDOOR = block(TheToolsAndOtherModBlocks.AQUA_TRAPDOOR);
	public static final DeferredItem<Item> AQUA_PRESSURE_PLATE = block(TheToolsAndOtherModBlocks.AQUA_PRESSURE_PLATE);
	public static final DeferredItem<Item> AQUA_BUTTOM = block(TheToolsAndOtherModBlocks.AQUA_BUTTOM);
	public static final DeferredItem<Item> AQUA_DARK_LOG = block(TheToolsAndOtherModBlocks.AQUA_DARK_LOG);
	public static final DeferredItem<Item> AQUA_DARK_PLANKS = block(TheToolsAndOtherModBlocks.AQUA_DARK_PLANKS);
	public static final DeferredItem<Item> AQUA_DARK_WOOD = block(TheToolsAndOtherModBlocks.AQUA_DARK_WOOD);
	public static final DeferredItem<Item> AQUA_DARK_DOOR = doubleBlock(TheToolsAndOtherModBlocks.AQUA_DARK_DOOR);
	public static final DeferredItem<Item> AQUA_DARK_TRAPDOOR = block(TheToolsAndOtherModBlocks.AQUA_DARK_TRAPDOOR);
	public static final DeferredItem<Item> AQUA_DARK_PRESSURE_PLATE = block(TheToolsAndOtherModBlocks.AQUA_DARK_PRESSURE_PLATE);
	public static final DeferredItem<Item> AQUA_DARK_BUTTOM = block(TheToolsAndOtherModBlocks.AQUA_DARK_BUTTOM);
	public static final DeferredItem<Item> AQUA_DARK_FENCE = block(TheToolsAndOtherModBlocks.AQUA_DARK_FENCE);
	public static final DeferredItem<Item> AQUA_DARK_FENCE_GATE = block(TheToolsAndOtherModBlocks.AQUA_DARK_FENCE_GATE);
	public static final DeferredItem<Item> AQUA_ARMOR_HELMET = register("aqua_armor_helmet", AquaArmorItem.Helmet::new);
	public static final DeferredItem<Item> AQUA_ARMOR_CHESTPLATE = register("aqua_armor_chestplate", AquaArmorItem.Chestplate::new);
	public static final DeferredItem<Item> AQUA_ARMOR_LEGGINGS = register("aqua_armor_leggings", AquaArmorItem.Leggings::new);
	public static final DeferredItem<Item> AQUA_ARMOR_BOOTS = register("aqua_armor_boots", AquaArmorItem.Boots::new);
	public static final DeferredItem<Item> MAGNE_ARMOR_HELMET = register("magne_armor_helmet", MagneArmorItem.Helmet::new);
	public static final DeferredItem<Item> MAGNE_ARMOR_CHESTPLATE = register("magne_armor_chestplate", MagneArmorItem.Chestplate::new);
	public static final DeferredItem<Item> MAGNE_ARMOR_LEGGINGS = register("magne_armor_leggings", MagneArmorItem.Leggings::new);
	public static final DeferredItem<Item> MAGNE_ARMOR_BOOTS = register("magne_armor_boots", MagneArmorItem.Boots::new);
	public static final DeferredItem<Item> AQUA_DARK_ARMOR_HELMET = register("aqua_dark_armor_helmet", AquaDarkArmorItem.Helmet::new);
	public static final DeferredItem<Item> AQUA_DARK_ARMOR_CHESTPLATE = register("aqua_dark_armor_chestplate", AquaDarkArmorItem.Chestplate::new);
	public static final DeferredItem<Item> AQUA_DARK_ARMOR_LEGGINGS = register("aqua_dark_armor_leggings", AquaDarkArmorItem.Leggings::new);
	public static final DeferredItem<Item> AQUA_DARK_ARMOR_BOOTS = register("aqua_dark_armor_boots", AquaDarkArmorItem.Boots::new);
	public static final DeferredItem<Item> MAGNE_PICKAXE = register("magne_pickaxe", MagnePickaxeItem::new);
	public static final DeferredItem<Item> MAGNE_AXE = register("magne_axe", MagneAxeItem::new);
	public static final DeferredItem<Item> MAGNE_SWORD = register("magne_sword", MagneSwordItem::new);
	public static final DeferredItem<Item> MAGNE_SHOVEL = register("magne_shovel", MagneShovelItem::new);
	public static final DeferredItem<Item> MAGNE_HOE = register("magne_hoe", MagneHoeItem::new);
	public static final DeferredItem<Item> AQUA_PICKAXE = register("aqua_pickaxe", AquaPickaxeItem::new);
	public static final DeferredItem<Item> AQUA_AXE = register("aqua_axe", AquaAxeItem::new);
	public static final DeferredItem<Item> AQUA_SWORD = register("aqua_sword", AquaSwordItem::new);
	public static final DeferredItem<Item> AQUA_SHOVEL = register("aqua_shovel", AquaShovelItem::new);
	public static final DeferredItem<Item> AQUA_HOE = register("aqua_hoe", AquaHoeItem::new);
	public static final DeferredItem<Item> AQUA_DARK_PICKAXE = register("aqua_dark_pickaxe", AquaDarkPickaxeItem::new);
	public static final DeferredItem<Item> AQUA_DARK_AXE = register("aqua_dark_axe", AquaDarkAxeItem::new);
	public static final DeferredItem<Item> AQUA_DARK_SWORD = register("aqua_dark_sword", AquaDarkSwordItem::new);
	public static final DeferredItem<Item> AQUA_DARK_SHOVEL = register("aqua_dark_shovel", AquaDarkShovelItem::new);
	public static final DeferredItem<Item> AQUA_DARK_HOE = register("aqua_dark_hoe", AquaDarkHoeItem::new);
	public static final DeferredItem<Item> BULL = block(TheToolsAndOtherModBlocks.BULL);
	public static final DeferredItem<Item> RED_ARMOR_HELMET = register("red_armor_helmet", RedArmorItem.Helmet::new);
	public static final DeferredItem<Item> RED_ARMOR_CHESTPLATE = register("red_armor_chestplate", RedArmorItem.Chestplate::new);
	public static final DeferredItem<Item> RED_ARMOR_LEGGINGS = register("red_armor_leggings", RedArmorItem.Leggings::new);
	public static final DeferredItem<Item> RED_ARMOR_BOOTS = register("red_armor_boots", RedArmorItem.Boots::new);
	public static final DeferredItem<Item> RED_REINFORCED_PICKAXE = register("red_reinforced_pickaxe", RedReinforcedPickaxeItem::new);
	public static final DeferredItem<Item> RED_REINFORCED_AXE = register("red_reinforced_axe", RedReinforcedAxeItem::new);
	public static final DeferredItem<Item> RED_REINFORCED_SWORD = register("red_reinforced_sword", RedReinforcedSwordItem::new);
	public static final DeferredItem<Item> RED_REINFORCED_SHOVEL = register("red_reinforced_shovel", RedReinforcedShovelItem::new);
	public static final DeferredItem<Item> RED_REINFORCED_HOE = register("red_reinforced_hoe", RedReinforcedHoeItem::new);
	public static final DeferredItem<Item> LIGHT_BLUE_WATER_BUCKET = register("light_blue_water_bucket", LightBlueWaterItem::new);
	public static final DeferredItem<Item> AQUA_LEAVES = block(TheToolsAndOtherModBlocks.AQUA_LEAVES);
	public static final DeferredItem<Item> MAGNE_LEAVES = block(TheToolsAndOtherModBlocks.MAGNE_LEAVES);
	public static final DeferredItem<Item> ARBUST = block(TheToolsAndOtherModBlocks.ARBUST);
	public static final DeferredItem<Item> AQUA_DARK_LEAVES = block(TheToolsAndOtherModBlocks.AQUA_DARK_LEAVES);
	public static final DeferredItem<Item> RED_EMERALD_ORE = block(TheToolsAndOtherModBlocks.RED_EMERALD_ORE);
	public static final DeferredItem<Item> RED_EMERALD_FRAGMENT = register("red_emerald_fragment", RedEmeraldFragmentItem::new);
	public static final DeferredItem<Item> RED_EMERALD_ORE_DEEPSLATE = block(TheToolsAndOtherModBlocks.RED_EMERALD_ORE_DEEPSLATE);
	public static final DeferredItem<Item> RED_EMERALD = block(TheToolsAndOtherModBlocks.RED_EMERALD);
	public static final DeferredItem<Item> RED_EMERALD_A_ARMOR_HELMET = register("red_emerald_a_armor_helmet", RedEmeraldAArmorItem.Helmet::new);
	public static final DeferredItem<Item> RED_EMERALD_A_ARMOR_CHESTPLATE = register("red_emerald_a_armor_chestplate", RedEmeraldAArmorItem.Chestplate::new);
	public static final DeferredItem<Item> RED_EMERALD_A_ARMOR_LEGGINGS = register("red_emerald_a_armor_leggings", RedEmeraldAArmorItem.Leggings::new);
	public static final DeferredItem<Item> RED_EMERALD_A_ARMOR_BOOTS = register("red_emerald_a_armor_boots", RedEmeraldAArmorItem.Boots::new);
	public static final DeferredItem<Item> RED_PICKAXE = register("red_pickaxe", RedPickaxeItem::new);
	public static final DeferredItem<Item> RED_AXE = register("red_axe", RedAxeItem::new);
	public static final DeferredItem<Item> RED_SWORD = register("red_sword", RedSwordItem::new);
	public static final DeferredItem<Item> RED_SHOVEL = register("red_shovel", RedShovelItem::new);
	public static final DeferredItem<Item> RED_HOE = register("red_hoe", RedHoeItem::new);
	public static final DeferredItem<Item> EMERALD_A_PICKAXE = register("emerald_a_pickaxe", EmeraldAPickaxeItem::new);
	public static final DeferredItem<Item> EMERALD_A_AXE = register("emerald_a_axe", EmeraldAAxeItem::new);
	public static final DeferredItem<Item> EMERALD_A_SWORD = register("emerald_a_sword", EmeraldASwordItem::new);
	public static final DeferredItem<Item> EMERALD_A_SHOVEL = register("emerald_a_shovel", EmeraldAShovelItem::new);
	public static final DeferredItem<Item> EMERALD_A_HOE = register("emerald_a_hoe", EmeraldAHoeItem::new);
	public static final DeferredItem<Item> EMERALDA_ARMOR_HELMET = register("emeralda_armor_helmet", EmeraldaArmorItem.Helmet::new);
	public static final DeferredItem<Item> EMERALDA_ARMOR_CHESTPLATE = register("emeralda_armor_chestplate", EmeraldaArmorItem.Chestplate::new);
	public static final DeferredItem<Item> EMERALDA_ARMOR_LEGGINGS = register("emeralda_armor_leggings", EmeraldaArmorItem.Leggings::new);
	public static final DeferredItem<Item> EMERALDA_ARMOR_BOOTS = register("emeralda_armor_boots", EmeraldaArmorItem.Boots::new);
	public static final DeferredItem<Item> LIGHTBLUE_WOOD = block(TheToolsAndOtherModBlocks.LIGHTBLUE_WOOD);
	public static final DeferredItem<Item> MONEY = block(TheToolsAndOtherModBlocks.MONEY);
	public static final DeferredItem<Item> MONEYY = register("moneyy", MoneyyItem::new);
	public static final DeferredItem<Item> CANDYBASTON = register("candybaston", CandybastonItem::new);
	public static final DeferredItem<Item> CANDY = block(TheToolsAndOtherModBlocks.CANDY);
	public static final DeferredItem<Item> ENREDADERA = block(TheToolsAndOtherModBlocks.ENREDADERA);
	public static final DeferredItem<Item> ENREDADERA_2 = block(TheToolsAndOtherModBlocks.ENREDADERA_2);
	public static final DeferredItem<Item> ENREDADERA_3 = block(TheToolsAndOtherModBlocks.ENREDADERA_3);
	public static final DeferredItem<Item> ONE_HUNDRED_DOLLARS = register("one_hundred_dollars", OneHundredDollarsItem::new);
	public static final DeferredItem<Item> PIZZA = register("pizza", PizzaItem::new);
	public static final DeferredItem<Item> RODAJA_DE_PIZZA = register("rodaja_de_pizza", RodajaDePizzaItem::new);
	public static final DeferredItem<Item> CORTADOR = register("cortador", CortadorItem::new);
	public static final DeferredItem<Item> MID_NIGHT = block(TheToolsAndOtherModBlocks.MID_NIGHT);
	public static final DeferredItem<Item> MOON = block(TheToolsAndOtherModBlocks.MOON);
	public static final DeferredItem<Item> SUN = block(TheToolsAndOtherModBlocks.SUN);
	public static final DeferredItem<Item> MILK_BUCKET = register("milk_bucket", MilkItem::new);
	public static final DeferredItem<Item> CURSED_BUCKET = register("cursed_bucket", CursedItem::new);
	public static final DeferredItem<Item> COLOSAL_GRASS = block(TheToolsAndOtherModBlocks.COLOSAL_GRASS);
	public static final DeferredItem<Item> COLOSAL = register("colosal", ColosalItem::new);
	public static final DeferredItem<Item> BOTTLE = register("bottle", BottleItem::new);
	public static final DeferredItem<Item> STRAWBERRY_NUTELLA = register("strawberry_nutella", StrawberryNutellaItem::new);
	public static final DeferredItem<Item> CHOCOLATE_NUTELLA = register("chocolate_nutella", ChocolateNutellaItem::new);
	public static final DeferredItem<Item> VAINILLA_NUTELLA = register("vainilla_nutella", VainillaNutellaItem::new);
	public static final DeferredItem<Item> MAGNIF_HELMET = register("magnif_helmet", MagnifItem.Helmet::new);
	public static final DeferredItem<Item> MAGNIF_CHESTPLATE = register("magnif_chestplate", MagnifItem.Chestplate::new);
	public static final DeferredItem<Item> MAGNIF_LEGGINGS = register("magnif_leggings", MagnifItem.Leggings::new);
	public static final DeferredItem<Item> MAGNIF_BOOTS = register("magnif_boots", MagnifItem.Boots::new);
	public static final DeferredItem<Item> MAGNIF_BLOCK = block(TheToolsAndOtherModBlocks.MAGNIF_BLOCK);
	public static final DeferredItem<Item> MAGNIF_INGOT = register("magnif_ingot", MagnifIngotItem::new);
	public static final DeferredItem<Item> GREEN_APPLE_JUICE_VOID = register("green_apple_juice_void", GreenAppleJuiceVoidItem::new);
	public static final DeferredItem<Item> GREE_APPLE_JUICE = register("gree_apple_juice", GreeAppleJuiceItem::new);
	public static final DeferredItem<Item> RED_APPLE_JUICE_VOID = register("red_apple_juice_void", RedAppleJuiceVoidItem::new);
	public static final DeferredItem<Item> RED_APPLE_JUICE = register("red_apple_juice", RedAppleJuiceItem::new);
	public static final DeferredItem<Item> FIFTY_DOLLAR = register("fifty_dollar", FiftyDollarItem::new);
	public static final DeferredItem<Item> FIVE_DOLLARS = register("five_dollars", FiveDollarsItem::new);
	public static final DeferredItem<Item> COLSITEM = register("colsitem", ColsitemItem::new);
	public static final DeferredItem<Item> COLSITEM_B = block(TheToolsAndOtherModBlocks.COLSITEM_B);
	public static final DeferredItem<Item> PENTIST_BLOCK = block(TheToolsAndOtherModBlocks.PENTIST_BLOCK);
	public static final DeferredItem<Item> PENTIST_INGOT = register("pentist_ingot", PentistIngotItem::new);
	public static final DeferredItem<Item> PENTIST_HELMET = register("pentist_helmet", PentistItem.Helmet::new);
	public static final DeferredItem<Item> PENTIST_CHESTPLATE = register("pentist_chestplate", PentistItem.Chestplate::new);
	public static final DeferredItem<Item> PENTIST_LEGGINGS = register("pentist_leggings", PentistItem.Leggings::new);
	public static final DeferredItem<Item> PENTIST_BOOTS = register("pentist_boots", PentistItem.Boots::new);
	public static final DeferredItem<Item> BLASTING_FURNACE = block(TheToolsAndOtherModBlocks.BLASTING_FURNACE);
	public static final DeferredItem<Item> GLASS_CHEST = block(TheToolsAndOtherModBlocks.GLASS_CHEST);
	public static final DeferredItem<Item> IRON_CHEST = block(TheToolsAndOtherModBlocks.IRON_CHEST);
	public static final DeferredItem<Item> DIAMOND_CHEST = block(TheToolsAndOtherModBlocks.DIAMOND_CHEST);
	public static final DeferredItem<Item> DUCK_SPAWN_EGG = register("duck_spawn_egg", properties -> new SpawnEggItem(TheToolsAndOtherModEntities.DUCK.get(), properties));
	public static final DeferredItem<Item> MATIST_SPAWN_EGG = register("matist_spawn_egg", properties -> new SpawnEggItem(TheToolsAndOtherModEntities.MATIST.get(), properties));
	public static final DeferredItem<Item> BEDROCK_ARMOR_HELMET = register("bedrock_armor_helmet", BedrockArmorItem.Helmet::new);
	public static final DeferredItem<Item> BEDROCK_ARMOR_CHESTPLATE = register("bedrock_armor_chestplate", BedrockArmorItem.Chestplate::new);
	public static final DeferredItem<Item> BEDROCK_ARMOR_LEGGINGS = register("bedrock_armor_leggings", BedrockArmorItem.Leggings::new);
	public static final DeferredItem<Item> BEDROCK_ARMOR_BOOTS = register("bedrock_armor_boots", BedrockArmorItem.Boots::new);
	public static final DeferredItem<Item> OPTINIUM_ROT = register("optinium_rot", OptiniumRotItem::new);
	public static final DeferredItem<Item> OPTINIUM_PICKAXE = register("optinium_pickaxe", OptiniumPickaxeItem::new);
	public static final DeferredItem<Item> OPTINIUM_AXE = register("optinium_axe", OptiniumAxeItem::new);
	public static final DeferredItem<Item> OPTINIUM_HAMMER = register("optinium_hammer", OptiniumHammerItem::new);
	public static final DeferredItem<Item> OPTINIUM = block(TheToolsAndOtherModBlocks.OPTINIUM);
	public static final DeferredItem<Item> OPTINIUM_ORE = block(TheToolsAndOtherModBlocks.OPTINIUM_ORE);
	public static final DeferredItem<Item> OPTINIUM_INGOT = register("optinium_ingot", OptiniumIngotItem::new);
	public static final DeferredItem<Item> DIAMOND_HAMMER_3D = register("diamond_hammer_3d", DiamondHammer3dItem::new);
	public static final DeferredItem<Item> MOSSY_BLUE_BRICKS = block(TheToolsAndOtherModBlocks.MOSSY_BLUE_BRICKS);
	public static final DeferredItem<Item> BLUE_BRICKS = block(TheToolsAndOtherModBlocks.BLUE_BRICKS);
	public static final DeferredItem<Item> BLUE_REINFORCED_BRICKS = block(TheToolsAndOtherModBlocks.BLUE_REINFORCED_BRICKS);
	public static final DeferredItem<Item> TOXIC_BUCKET = register("toxic_bucket", ToxicItem::new);
	public static final DeferredItem<Item> REDSTONE_APPLE = register("redstone_apple", RedstoneAppleItem::new);
	public static final DeferredItem<Item> REDSTONE_ENCHANTED_APPLE = register("redstone_enchanted_apple", RedstoneEnchantedAppleItem::new);
	public static final DeferredItem<Item> DIAMOND_APPLE = register("diamond_apple", DiamondAppleItem::new);
	public static final DeferredItem<Item> ENCHANTED_DIAMOND_APPLE = register("enchanted_diamond_apple", EnchantedDiamondAppleItem::new);
	public static final DeferredItem<Item> GOLD_PORKCHOP = register("gold_porkchop", GoldPorkchopItem::new);
	public static final DeferredItem<Item> GOLD_PORKCHOP_COOKED = register("gold_porkchop_cooked", GoldPorkchopCookedItem::new);
	public static final DeferredItem<Item> CREEPER_HELMET = register("creeper_helmet", CreeperItem.Helmet::new);
	public static final DeferredItem<Item> CREEPER_CHESTPLATE = register("creeper_chestplate", CreeperItem.Chestplate::new);
	public static final DeferredItem<Item> CREEPER_LEGGINGS = register("creeper_leggings", CreeperItem.Leggings::new);
	public static final DeferredItem<Item> CREEPER_BOOTS = register("creeper_boots", CreeperItem.Boots::new);
	public static final DeferredItem<Item> BLUE_BRICK_ARMOR_HELMET = register("blue_brick_armor_helmet", BlueBrickArmorItem.Helmet::new);
	public static final DeferredItem<Item> BLUE_BRICK_ARMOR_CHESTPLATE = register("blue_brick_armor_chestplate", BlueBrickArmorItem.Chestplate::new);
	public static final DeferredItem<Item> BLUE_BRICK_ARMOR_LEGGINGS = register("blue_brick_armor_leggings", BlueBrickArmorItem.Leggings::new);
	public static final DeferredItem<Item> BLUE_BRICK_ARMOR_BOOTS = register("blue_brick_armor_boots", BlueBrickArmorItem.Boots::new);
	public static final DeferredItem<Item> STRAWBERRY = register("strawberry", StrawberryItem::new);
	public static final DeferredItem<Item> FANTIST = register("fantist", FantistItem::new);
	public static final DeferredItem<Item> FOLLIAGE_BLOCK = block(TheToolsAndOtherModBlocks.FOLLIAGE_BLOCK);
	public static final DeferredItem<Item> FOLLIAGE_DOOR = doubleBlock(TheToolsAndOtherModBlocks.FOLLIAGE_DOOR);
	public static final DeferredItem<Item> WINDOW = block(TheToolsAndOtherModBlocks.WINDOW);
	public static final DeferredItem<Item> ROCKYS_SPAWN_EGG = register("rockys_spawn_egg", properties -> new SpawnEggItem(TheToolsAndOtherModEntities.ROCKYS.get(), properties));
	public static final DeferredItem<Item> BLOOD = block(TheToolsAndOtherModBlocks.BLOOD);
	public static final DeferredItem<Item> BLOOD_1 = block(TheToolsAndOtherModBlocks.BLOOD_1);
	public static final DeferredItem<Item> NETHERITE_CHEST = block(TheToolsAndOtherModBlocks.NETHERITE_CHEST);
	public static final DeferredItem<Item> BOX_OF_PIZZA = block(TheToolsAndOtherModBlocks.BOX_OF_PIZZA);
	public static final DeferredItem<Item> PIZZA_V_2 = register("pizza_v_2", PizzaV2Item::new);
	public static final DeferredItem<Item> MACE = register("mace", MaceItem::new);
	public static final DeferredItem<Item> SWORDS = register("swords", SwordsItem::new);
	public static final DeferredItem<Item> AIR = register("air", AirItem::new);
	public static final DeferredItem<Item> AXOLTL_BOOTS = register("axoltl_boots", AxoltlItem.Boots::new);
	public static final DeferredItem<Item> RED_VOLCANIC = block(TheToolsAndOtherModBlocks.RED_VOLCANIC);
	public static final DeferredItem<Item> VOLCANIC = block(TheToolsAndOtherModBlocks.VOLCANIC);
	public static final DeferredItem<Item> YELLOW_VOLCANIC = block(TheToolsAndOtherModBlocks.YELLOW_VOLCANIC);
	public static final DeferredItem<Item> GREEN_VOLCANIC = block(TheToolsAndOtherModBlocks.GREEN_VOLCANIC);
	public static final DeferredItem<Item> BLUE_VOLCANIC = block(TheToolsAndOtherModBlocks.BLUE_VOLCANIC);
	public static final DeferredItem<Item> GREEN_OAK = block(TheToolsAndOtherModBlocks.GREEN_OAK);
	public static final DeferredItem<Item> GREEN_OAK_LEAVES = block(TheToolsAndOtherModBlocks.GREEN_OAK_LEAVES);
	public static final DeferredItem<Item> GREEN_PLANKS = block(TheToolsAndOtherModBlocks.GREEN_PLANKS);
	public static final DeferredItem<Item> GREEN_OAK_WOOD = block(TheToolsAndOtherModBlocks.GREEN_OAK_WOOD);
	public static final DeferredItem<Item> YELLOW_WATER_BUCKET = register("yellow_water_bucket", YellowWaterItem::new);
	public static final DeferredItem<Item> PINK_WATER_BUCKET = register("pink_water_bucket", PinkWaterItem::new);
	public static final DeferredItem<Item> PURPLE_WATER_BUCKET = register("purple_water_bucket", PurpleWaterItem::new);
	public static final DeferredItem<Item> WATER_BUCKET = register("water_bucket", WaterItem::new);
	public static final DeferredItem<Item> CLITPALLS_BLOCK = block(TheToolsAndOtherModBlocks.CLITPALLS_BLOCK);
	public static final DeferredItem<Item> FOLLIAGE_TRAPDOOR = block(TheToolsAndOtherModBlocks.FOLLIAGE_TRAPDOOR);
	public static final DeferredItem<Item> FOLLIAGE_FRAGMENT = register("folliage_fragment", FolliageFragmentItem::new);
	public static final DeferredItem<Item> FOLLIAGE_FENCE = block(TheToolsAndOtherModBlocks.FOLLIAGE_FENCE);
	public static final DeferredItem<Item> FOLLIAGE_FENCE_GATE = block(TheToolsAndOtherModBlocks.FOLLIAGE_FENCE_GATE);
	public static final DeferredItem<Item> FOLLIAGE_STAIR = block(TheToolsAndOtherModBlocks.FOLLIAGE_STAIR);
	public static final DeferredItem<Item> FOLLIAGE_SLAB = block(TheToolsAndOtherModBlocks.FOLLIAGE_SLAB);
	public static final DeferredItem<Item> FOLLIAGE_BOTTOM = block(TheToolsAndOtherModBlocks.FOLLIAGE_BOTTOM);
	public static final DeferredItem<Item> FOLLIAGE_PRESSURE_PLATE = block(TheToolsAndOtherModBlocks.FOLLIAGE_PRESSURE_PLATE);
	public static final DeferredItem<Item> FOLLIAGE_WALL = block(TheToolsAndOtherModBlocks.FOLLIAGE_WALL);
	public static final DeferredItem<Item> GREEN_OAK_DOOR = doubleBlock(TheToolsAndOtherModBlocks.GREEN_OAK_DOOR);
	public static final DeferredItem<Item> GREEN_OAK_TRAP_DOOR = block(TheToolsAndOtherModBlocks.GREEN_OAK_TRAP_DOOR);
	public static final DeferredItem<Item> SIRPINT_LOG = block(TheToolsAndOtherModBlocks.SIRPINT_LOG);
	public static final DeferredItem<Item> SIRPINT_PLANKS = block(TheToolsAndOtherModBlocks.SIRPINT_PLANKS);
	public static final DeferredItem<Item> SIRPINT_WOOD = block(TheToolsAndOtherModBlocks.SIRPINT_WOOD);
	public static final DeferredItem<Item> LIGHT_BLUE_SAND = block(TheToolsAndOtherModBlocks.LIGHT_BLUE_SAND);
	public static final DeferredItem<Item> BLUE_SAND = block(TheToolsAndOtherModBlocks.BLUE_SAND);
	public static final DeferredItem<Item> YELLOW_SAND = block(TheToolsAndOtherModBlocks.YELLOW_SAND);
	public static final DeferredItem<Item> GREEN_SAND = block(TheToolsAndOtherModBlocks.GREEN_SAND);
	public static final DeferredItem<Item> RED_SAND = block(TheToolsAndOtherModBlocks.RED_SAND);
	public static final DeferredItem<Item> BLUE_SAND_STONE = block(TheToolsAndOtherModBlocks.BLUE_SAND_STONE);
	public static final DeferredItem<Item> GREEN_SAND_STONE = block(TheToolsAndOtherModBlocks.GREEN_SAND_STONE);
	public static final DeferredItem<Item> ORANGE_WATER_BUCKET = register("orange_water_bucket", OrangeWaterItem::new);
	public static final DeferredItem<Item> GRAPE_LOG = block(TheToolsAndOtherModBlocks.GRAPE_LOG);
	public static final DeferredItem<Item> GRAPE_LEAVES = block(TheToolsAndOtherModBlocks.GRAPE_LEAVES);
	public static final DeferredItem<Item> GRAPE = register("grape", GrapeItem::new);
	public static final DeferredItem<Item> ARCOIRIS_WATER_BUCKET = register("arcoiris_water_bucket", ArcoirisWaterItem::new);
	public static final DeferredItem<Item> PETROLLEO_BUCKET = register("petrolleo_bucket", PetrolleoItem::new);
	public static final DeferredItem<Item> YELLOW_SAND_STONE = block(TheToolsAndOtherModBlocks.YELLOW_SAND_STONE);
	public static final DeferredItem<Item> FRIDGE = block(TheToolsAndOtherModBlocks.FRIDGE);
	public static final DeferredItem<Item> DIRT_HELMET = register("dirt_helmet", DirtItem.Helmet::new);
	public static final DeferredItem<Item> DIRT_CHESTPLATE = register("dirt_chestplate", DirtItem.Chestplate::new);
	public static final DeferredItem<Item> DIRT_LEGGINGS = register("dirt_leggings", DirtItem.Leggings::new);
	public static final DeferredItem<Item> DIRT_BOOTS = register("dirt_boots", DirtItem.Boots::new);
	public static final DeferredItem<Item> STONE_HELMET = register("stone_helmet", StoneItem.Helmet::new);
	public static final DeferredItem<Item> STONE_CHESTPLATE = register("stone_chestplate", StoneItem.Chestplate::new);
	public static final DeferredItem<Item> STONE_LEGGINGS = register("stone_leggings", StoneItem.Leggings::new);
	public static final DeferredItem<Item> STONE_BOOTS = register("stone_boots", StoneItem.Boots::new);
	public static final DeferredItem<Item> METAL_BLOCK = block(TheToolsAndOtherModBlocks.METAL_BLOCK);
	public static final DeferredItem<Item> METAL_INGOT = register("metal_ingot", MetalIngotItem::new);
	public static final DeferredItem<Item> METAL_SWORD = register("metal_sword", MetalSwordItem::new);
	public static final DeferredItem<Item> METAL_PICKAXE = register("metal_pickaxe", MetalPickaxeItem::new);
	public static final DeferredItem<Item> METAL_AXE = register("metal_axe", MetalAxeItem::new);
	public static final DeferredItem<Item> METAL_SHOVEL = register("metal_shovel", MetalShovelItem::new);
	public static final DeferredItem<Item> METAL_HOE = register("metal_hoe", MetalHoeItem::new);
	public static final DeferredItem<Item> METAL_HELMET = register("metal_helmet", MetalItem.Helmet::new);
	public static final DeferredItem<Item> METAL_CHESTPLATE = register("metal_chestplate", MetalItem.Chestplate::new);
	public static final DeferredItem<Item> METAL_LEGGINGS = register("metal_leggings", MetalItem.Leggings::new);
	public static final DeferredItem<Item> METAL_BOOTS = register("metal_boots", MetalItem.Boots::new);
	public static final DeferredItem<Item> METAL_ORE = block(TheToolsAndOtherModBlocks.METAL_ORE);
	public static final DeferredItem<Item> RED_DIAMOND_BLOCK = block(TheToolsAndOtherModBlocks.RED_DIAMOND_BLOCK);
	public static final DeferredItem<Item> RED_DIAMOND_INGOT = register("red_diamond_ingot", RedDiamondIngotItem::new);
	public static final DeferredItem<Item> RED_DIAMOND_HELMET = register("red_diamond_helmet", RedDiamondItem.Helmet::new);
	public static final DeferredItem<Item> RED_DIAMOND_CHESTPLATE = register("red_diamond_chestplate", RedDiamondItem.Chestplate::new);
	public static final DeferredItem<Item> RED_DIAMOND_LEGGINGS = register("red_diamond_leggings", RedDiamondItem.Leggings::new);
	public static final DeferredItem<Item> RED_DIAMOND_BOOTS = register("red_diamond_boots", RedDiamondItem.Boots::new);
	public static final DeferredItem<Item> RED_DIAMOND_SWORD = register("red_diamond_sword", RedDiamondSwordItem::new);
	public static final DeferredItem<Item> RED_DIAMOND_PICKAXE = register("red_diamond_pickaxe", RedDiamondPickaxeItem::new);
	public static final DeferredItem<Item> RED_DIAMOND_AXE = register("red_diamond_axe", RedDiamondAxeItem::new);
	public static final DeferredItem<Item> RED_DIAMOND_SHOVEL = register("red_diamond_shovel", RedDiamondShovelItem::new);
	public static final DeferredItem<Item> RED_DIAMOND_HOE = register("red_diamond_hoe", RedDiamondHoeItem::new);
	public static final DeferredItem<Item> GREEN_DIAMOND_BLOCK = block(TheToolsAndOtherModBlocks.GREEN_DIAMOND_BLOCK);
	public static final DeferredItem<Item> RED_DIAMOND_ORE = block(TheToolsAndOtherModBlocks.RED_DIAMOND_ORE);
	public static final DeferredItem<Item> GREEN_DIAMOND_INGOT = register("green_diamond_ingot", GreenDiamondIngotItem::new);
	public static final DeferredItem<Item> GREEN_DIAMOND_HELMET = register("green_diamond_helmet", GreenDiamondItem.Helmet::new);
	public static final DeferredItem<Item> GREEN_DIAMOND_CHESTPLATE = register("green_diamond_chestplate", GreenDiamondItem.Chestplate::new);
	public static final DeferredItem<Item> GREEN_DIAMOND_LEGGINGS = register("green_diamond_leggings", GreenDiamondItem.Leggings::new);
	public static final DeferredItem<Item> GREEN_DIAMOND_BOOTS = register("green_diamond_boots", GreenDiamondItem.Boots::new);
	public static final DeferredItem<Item> GREEN_DIAMOND_SWORD = register("green_diamond_sword", GreenDiamondSwordItem::new);
	public static final DeferredItem<Item> GREEN_DIAMOND_PICKAXE = register("green_diamond_pickaxe", GreenDiamondPickaxeItem::new);
	public static final DeferredItem<Item> GREEN_DIAMOND_AXE = register("green_diamond_axe", GreenDiamondAxeItem::new);
	public static final DeferredItem<Item> GREEN_DIAMOND_SHOVEL = register("green_diamond_shovel", GreenDiamondShovelItem::new);
	public static final DeferredItem<Item> GREEN_DIAMOND_HOE = register("green_diamond_hoe", GreenDiamondHoeItem::new);
	public static final DeferredItem<Item> GREEN_DIAMOND_ORE = block(TheToolsAndOtherModBlocks.GREEN_DIAMOND_ORE);
	public static final DeferredItem<Item> GOOD_TABLE = block(TheToolsAndOtherModBlocks.GOOD_TABLE);
	public static final DeferredItem<Item> TOTEM = register("totem", TotemItem::new);
	public static final DeferredItem<Item> RED_TOTEM = register("red_totem", RedTotemItem::new);
	public static final DeferredItem<Item> BLACK_TOTEM = register("black_totem", BlackTotemItem::new);
	public static final DeferredItem<Item> BLUE_DIAMOND_TOTEM = register("blue_diamond_totem", BlueDiamondTotemItem::new);
	public static final DeferredItem<Item> BROWN_WATER_BUCKET = register("brown_water_bucket", BrownWaterItem::new);
	public static final DeferredItem<Item> AQUA_WATER_BUCKET = register("aqua_water_bucket", AquaWaterItem::new);
	public static final DeferredItem<Item> BLUE_WATER_BUCKET = register("blue_water_bucket", BlueWaterItem::new);
	public static final DeferredItem<Item> YELLOW_DIAMOND_INGOT = register("yellow_diamond_ingot", YellowDiamondIngotItem::new);
	public static final DeferredItem<Item> YELLOW_DIAMOND_HELMET = register("yellow_diamond_helmet", YellowDiamondItem.Helmet::new);
	public static final DeferredItem<Item> YELLOW_DIAMOND_CHESTPLATE = register("yellow_diamond_chestplate", YellowDiamondItem.Chestplate::new);
	public static final DeferredItem<Item> YELLOW_DIAMOND_LEGGINGS = register("yellow_diamond_leggings", YellowDiamondItem.Leggings::new);
	public static final DeferredItem<Item> YELLOW_DIAMOND_BOOTS = register("yellow_diamond_boots", YellowDiamondItem.Boots::new);
	public static final DeferredItem<Item> YELLOW_DIAMOND_SWORD = register("yellow_diamond_sword", YellowDiamondSwordItem::new);
	public static final DeferredItem<Item> GOLD_MACE = register("gold_mace", GoldMaceItem::new);
	public static final DeferredItem<Item> TRUSTANIC_BLOCK = block(TheToolsAndOtherModBlocks.TRUSTANIC_BLOCK);
	public static final DeferredItem<Item> TRUSTANIC_ORE = block(TheToolsAndOtherModBlocks.TRUSTANIC_ORE);
	public static final DeferredItem<Item> COPSIDIAN = block(TheToolsAndOtherModBlocks.COPSIDIAN);
	public static final DeferredItem<Item> PALE_ARMOR_HELMET = register("pale_armor_helmet", PALEArmorItem.Helmet::new);
	public static final DeferredItem<Item> PALE_ARMOR_CHESTPLATE = register("pale_armor_chestplate", PALEArmorItem.Chestplate::new);
	public static final DeferredItem<Item> PALE_ARMOR_LEGGINGS = register("pale_armor_leggings", PALEArmorItem.Leggings::new);
	public static final DeferredItem<Item> PALE_ARMOR_BOOTS = register("pale_armor_boots", PALEArmorItem.Boots::new);

	// Start of user code block custom items
	// End of user code block custom items
	private static <I extends Item> DeferredItem<I> register(String name, Function<Item.Properties, ? extends I> supplier) {
		return REGISTRY.registerItem(name, supplier, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return REGISTRY.registerItem(block.getId().getPath(), properties -> new BlockItem(block.get(), properties), new Item.Properties());
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block) {
		return REGISTRY.registerItem(block.getId().getPath(), properties -> new DoubleHighBlockItem(block.get(), properties), new Item.Properties());
	}
}
